config/routes.rb
TestApp::Application.routes.draw do
  get "users/new"

  mathjax 'mathjax'
  root to: 'static_pages#home'

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  resources :resumes, only: [ :home, :createpage, :create, :postdata , :checkdata, :viewlist, :viewedit , :delete, :createtemplate, :cssapi, :checkcssfile, :postcssfile] 

  resources :homepages, only: [ :home, :create, :postdata, :view, :delete, :download, :checkdata, :cssapi ]

  match '/signup', to: "users#new"
  match "/help", to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/resumes', to: 'resumes#home'
  match '/resumes/createpage', to: 'resumes#createpage'
  match '/homepages', to: 'homepages#home'

  
  match '/resumes/postdata', to: 'resumes#postdata', via: :post
  match '/resumes/checkdata', to: 'resumes#checkdata', via: :get
  match '/resumes/viewlist', to: 'resumes#viewlist'
  match '/resumes/viewedit', to: 'resumes#viewedit'
  match '/resumes/delete', to: 'resumes#delete'
  match '/resumes/createtemplate', to: 'resumes#createtemplate'
  match '/resumes/download', to: 'resumes#download'
  match '/resumes/cssapi', to: "resumes#cssapi", via: :get
  match '/resumes/checkcssfile', to: "resumes#checkcssfile", via: :get
  match '/resumes/postcssfile', to: "resumes#postcssfile", via: :post

  match '/homepages/create', to: 'homepages#create'
  match '/homepages/postdata',to: 'homepages#postdata', via: :post
  match '/homepages/view', to:'homepages#view'
  match '/homepages/delete', to:'homepages#delete'
  match '/homepages/checkdata', to:'homepages#checkdata'
  match '/homepages/download', to:'homepages#download'
  match '/homepages/cssapi', to: "homepages#cssapi", via: :get

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title , 'About') %>
<h1> This is the about page </h1>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>Create professional resumes, CV and bio-data online for free, in minutes. Simply fill in your details and generate beautiful PDF and HTML resumes!</p>
<p></p>

app/views/static_pages/home.html.erb
<!-- <a href="#" class="btn btn-large btn-primary">Sign up</a> -->
<!--img alt="Rails" src="/assets/rails.png" /-->

<% if signed_in? %>
	<h1> Navigate to your preferred destination </h1>
	<div class="row">
		<%= button_to "Resume", resumes_path, :method => "get", class:'btn btn-large btn-primary' %>
		<%= button_to "Homepage", homepages_path, :method =>"get", class:'btn btn-large btn-primary' %>
	</div>
	<% else %>
	<h1> Please Login to continue </h1>
<% end %>