config/routes.rb
TestApp::Application.routes.draw do
  get "users/new"

  mathjax 'mathjax'
  root to: 'static_pages#home'

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  resources :resumes, only: [ :home, :createpage, :create, :postdata , :checkdata, :viewlist, :viewedit , :delete, :createtemplate, :cssapi, :checkcssfile, :postcssfile] 

  resources :homepages, only: [ :home, :create, :postdata, :view, :delete, :download, :checkdata, :cssapi ]

  match '/signup', to: "users#new"
  match "/help", to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/resumes', to: 'resumes#home'
  match '/resumes/createpage', to: 'resumes#createpage'
  match '/homepages', to: 'homepages#home'

  
  match '/resumes/postdata', to: 'resumes#postdata', via: :post
  match '/resumes/checkdata', to: 'resumes#checkdata', via: :get
  match '/resumes/viewlist', to: 'resumes#viewlist'
  match '/resumes/viewedit', to: 'resumes#viewedit'
  match '/resumes/delete', to: 'resumes#delete'
  match '/resumes/createtemplate', to: 'resumes#createtemplate'
  match '/resumes/download', to: 'resumes#download'
  match '/resumes/cssapi', to: "resumes#cssapi", via: :get
  match '/resumes/checkcssfile', to: "resumes#checkcssfile", via: :get
  match '/resumes/postcssfile', to: "resumes#postcssfile", via: :post

  match '/homepages/create', to: 'homepages#create'
  match '/homepages/postdata',to: 'homepages#postdata', via: :post
  match '/homepages/view', to:'homepages#view'
  match '/homepages/delete', to:'homepages#delete'
  match '/homepages/checkdata', to:'homepages#checkdata'
  match '/homepages/download', to:'homepages#download'
  match '/homepages/cssapi', to: "homepages#cssapi", via: :get

end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
  attr_accessible :homepage_name, :user_id, :homepage_html
  has_attached_file :homepage_html,
  	:path => ":rails_root/uploads_pages/:id/:basename.:extension"

  do_not_validate_attachment_file_type :homepage_html

  belongs_to :user
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController

	before_filter :signed_in_user, only: [ :home, :create, :postdata, :checkdata, :view ] 
	
	def home
	end
	
	def create
		@css_list = HomepagesCssTemplate.all
	end

	def postdata
		ActiveRecord::Base.transaction do
			@new_name = params[:rname]
			@old_r = current_user.homepages.find_by_homepage_name(@new_name)
			if !(@old_r.blank?) || (@new_name.blank?)
				flash[:error] = "You forcibly posted an invalid html file. Your html file will be lost"
				redirect_to root_url
			else
				bootstrap = File.read(Rails.root.join('public','bootstrap.min.css'));
				file = StringIO.new('<html><body><script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><style>'+bootstrap+'</style>' + params[:htmlpage] + '</body></html>')

				file.class.class_eval { attr_accessor :original_filename, :content_type }
	  			file.original_filename = @new_name + ".html"
	  			file.content_type = "text/html" # you could set this manually aswell if needed e.g 'application/pdf'
				current_user.homepages.build(homepage_name:@new_name, homepage_html: file).save()
			end
			file.close
		end
	end

	def checkdata
		@new_name = params[:rname]
		@old_r = current_user.homepages.find_by_homepage_name(@new_name)
		if @old_r.blank? && !(@new_name.blank?)
			render :json => {"valid" => "true"}
		else
			render :json => {"valid" => "false"}
		end
	end

	def view
		@homepage_list = current_user.homepages.all
	end

	def delete
		@page =  current_user.homepages.find(params[:homepage_id])
		@page.destroy
		flash[:success] = "Deleted the resume successfully"
		redirect_to resumes_viewlist_path
	end

	def download
		@homepage = current_user.homepages.find(params[:homepage_id])
		
		if @homepage.nil?
			flash[:error] = "Invalid parameters entered"
			redirect_to homepages_view_path
		end
		send_file @homepage.homepage_html.path, filename: @homepage.homepage_name, type: "text/html", disposition: 'inline'
	end

	def cssapi
		@css_fname = params[:css_template]
		send_data Paperclip.io_adapters.for(HomepagesCssTemplate.find_by_template_name(@css_fname).template_file).read
	end
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/views/homepages/create.html.erb
<%= provide(:title, "Create Homepage" ) %>
<link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Italianno' rel='stylesheet' type='text/css'>

<div id="create_page" class="row">
	<!-- <link href="ssg-style.css" rel="stylesheet"> -->
	<div class="col-md-6">
		<div id="homepage" class="page">

		</div>
	</div>
	<div class="col-md-6" id="form_div">
		<!-- move this to an appropriate file -->
		<%= form_tag(homepages_postdata_path, method: "post", id: "form") do %>
			<label class="fieldname">
				Template Name :
			</label>
			<select id="css_template" name="css_template" form="form" onchange="change_template()">
				<% @css_list.each do |item| %>
					<option value="<%= item.template_name %>"><%= item.template_name %></option>
				<% end %>
				<option>test</option>
			</select>
			<label class="fieldname">
				File Name :
			</label>
			<input id="rname" type="text" name="rname">
			<hr>
			<br>
			<label class="fieldname">
				Name :
			</label>
			<input id="name" type="text" name="name" onchange="updateResume()">
			<br>
			<label class="fieldname">
				About me :
			</label>
			<input id="aboutMe" type="text" name="aboutMe" onchange="updateResume()">
			<br>
			<div class="checkbox">
				<label class="fieldname">
					<button type="button" onclick="$('#contactgroup').slideToggle(); toggleUpDown();">^</button><input type="checkbox" id="contactcheck" name="contactcheck" checked> Contact :
				</label>
			</div>
			<div class="formgroup" id="contactgroup">
				<label>
					Email id :
				</label>
				<input id="email" type="text" name="email" onchange="updateResume()">
				<br>
				<label>
					Contact number :
				</label>
				<input id="contact" type="text" name="contact" onchange="updateResume()">
			</div>
			<div class="checkbox">
				<label class="fieldname">
					<button type="button" onclick="$('#educationgroup').slideToggle(); toggleUpDown();">^</button><input type="checkbox" id="educationcheck" name = "educationcheck" checked> Education :
				</label>
			</div>
			<div class="formgroup" id="educationgroup">
				<button type="button" onclick="addEducation()">+</button>
			</div>

			
			<div class="checkbox">
				<label class="fieldname">
					<button type="button" onclick="$('#acadAchievementsgroup').slideToggle(); toggleUpDown();">^</button><input type="checkbox" id="acadAchievementscheck" name="acadAchievementscheck"checked> Academic Achievements :
				</label>
			</div>
			<div class="formgroup" id="acadAchievementsgroup">
				<button type="button" onclick="addAcadAchievements()">+</button>
			</div>

			<!-- <div class="checkbox">
				<label class="fieldname">
					<button type="button" onclick="$('#workExperiencegroup').slideToggle(); toggleUpDown();">^</button><input type="checkbox" id="workExperiencecheck" name="workExperiencecheck"checked> Work Experience :
				</label>
			</div>
			<div class="formgroup" id="workExperiencegroup">
				<button type="button" onclick="addWorkExperience()">+</button>
			</div> -->

			<!-- <div class="checkbox">
				<label class="fieldname">
					<button type="button" onclick="$('#papersgroup').slideToggle(); toggleUpDown();">^</button><input type="checkbox" id="papercheck" name="papercheck"checked> Papers Published :
				</label>
			</div>
			<div class="formgroup" id="papersgroup">
				<button type="button" onclick="addPaper()">+</button>
			</div> -->

			<div class="checkbox">
				<label class="fieldname">
					<button type="button" onclick="$('#extraCgroup').slideToggle(); toggleUpDown();">^</button><input type="checkbox" id="extraCcheck" name="extraCcheck"checked> Extra Curricular Activities :
				</label>
			</div>
			<div class="formgroup" id="extraCgroup">
				<button type="button" onclick="addExtraC()">+</button>
			</div>

			<input type="submit" class="btn btn-primary">
			<input type="hidden" id="htmlpage" name="htmlpage" />
		<% end %>
	</div>
</div>

<!--<script src="http://builds.handlebarsjs.com.s3.amazonaws.com/handlebars-v1.3.0.js"></script>
<script src="http://builds.emberjs.com/tags/v1.5.0/ember.js"></script> -->


<script>
	var edu_index=0;
	var acadAchievements_index=0;
	var workExp_index=0;
	var paper_index=0;
	var extraC_index=0;
	var current_dynamic_css = '';
	function updateResume()
	{
		var data = "";
		data = data + '<div id="header">\
						    <div id="header-content">'
		data = data + getData("name");
		data = data + '</div>\
    					</div>'
    	data = data + '<div class="clear"></div>\
					    <div id="menu">\
    					<div id="menu-content">\
        				<div id="left-menu">\
        				<ul>'
        data = data + '<li><a href="#home">Home</a></li>'


        data = data + '<li><a href="#about">About Me</a></li>'

        if(check("educationcheck") || check("acadAchievementscheck"))
        	data = data + '<li><a href="#research">Academics</a></li>'

        if(check("extraCcheck"))
        	data = data + '<li><a href="#extra">Extra Curriculars</a></li>'

        if(check("contactcheck"))
        	data = data + '<li><a href="#personal">Contact</a></li>'

        data = data + '</ul>\
        				</div>\
        				</div>\
    					</div>'
  //   	data = data + '<div class="clear"></div>\
  //   					<div id="menugap"></div>\
		// 			    <div class="clear"></div>\
  //   					<div id="container">\
  //       				<div id="content">\
  //       				<div id="left-column">'
		// data = data + '</div>\
		// 		        <div id="mid-column">'
		data = data + '</div>\
				        <div id="left-mid-column">'

		data = data + '<h1>About Me\
				        <a class="anchor" id="about">about</a></h1>'
		data = data + getData("aboutMe");

        if(check("educationcheck") || check("acadAchievementscheck")){
        	data = data + '<h1>Academics\
				            <a class="anchor" id="research">research</a></h1>'

			if(check("educationcheck"))
			{
				data = data + '<font color="green"><b>Educational Qualifications:</b></font>'
				data = data + '<table class="table table-condensed">\
								  <tr>\
								  	<th>Class</th>\
								  	<th>Board / University</th>\
								  	<th>Year of Passing</th>\
								  	<th>Grade / percentage</th>\
								  </tr>'
				var i;
				for(i=0; i<edu_index; i++)
				{
					if(check("educheck"+i))
					{
						data = data + "<tr><td>"+getData("class"+i)+"</td><td>"+getData("board"+i)+"</td><td>"+getData("yearofpassing"+i)+"</td><td>"+getData("grade"+i)+"</td><td></tr>"
					}
				}
				data = data + "</table>";
			}

			if(check("acadAchievementscheck"))
			{
				data = data + '<font color="green"><b>Scholastic Achievements:</font></b><br>'
				data = data + '<ul class="list">'
				var i;
				for(i=0; i<acadAchievements_index; i++)
				{
					if(check("acadAchievcheck"+i))
					{
						data = data + "<li>" + getData("acadAchieve"+i)+"</li>"
					}
				}
				data = data + "</ul>";
			}

		}

		if(check("extraCcheck"))
		{
			data = data + '<h1>Extra Curriculars\
				            <a class="anchor" id="extra">extra</a></h1>'
			data = data + '<ul class="list">'
			var i;
			for(i=0; i<extraC_index; i++)
			{
				if(check("extraentrycheck"+i))
				{
					data = data + "<li>" + getData("extraentry"+i)+"</li>"
				}
			}
			data = data + "</ul>";
		}

		if(check("contactcheck"))
		{
			data = data + '<h1>Contact me\
				            <a class="anchor" id="personal">personal</a></h1>'
			data = data + '<font color="green">Email-id: </font>'
			data = data + getData("email") + "<br>";
			data = data + '<font color="green">Phone no.: </font>'
			data = data + getData("contact") + "<br>";
		}

		data = data + '</div>\
						</div>\
						</div>'
		data = data + '<div class="clear"></div>\
					    <div id="footer">\
    					<div id="footer-content">\
        				&copy; Me\
        				<br>\
        				Feedback is not welcome .\
    					</div>\
    					</div>'
    	data = data + "<style id='dynamic_css'>"+current_dynamic_css+"</style>";
		data = data + ''

		document.getElementById("homepage").innerHTML = data;

		$("#htmlpage").val(data)
		MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
		
	}
	function getData(field)
	{
		var s = document.getElementById(field).value;
		//write code to remove tags etc.
		// s=s.replace(/&amp;/g,'&amp;amp;');
		// s=s.replace(/&lt;/g,'&amp;lt;');
		// s=s.replace(/&gt;/g,'&amp;gt;');
		// s=s.replace(/\n/g,'&lt;br /&gt;\n');
		// s=s.replace(/\r/g,'');
		return s;
	}
	function check(str)
	{
		if(document.getElementById(str).checked)
			return true;
		else
			return false;
	}
	function addEducation()
	{
		var data = "";
		data =data + '<div class="checkbox">\
						<label class="fieldname">\
							<input type="checkbox" id="educheck'+edu_index+'" name =  "educheck'+edu_index+'"checked> Class :\
						</label>\
					</div>\
					<input id="class'+edu_index+'" type="text" name="class'+edu_index+'" onchange="updateResume()">\
					<br>\
					<label>\
						Board / University\
					</label>\
					<input id="board'+edu_index+'" type="text" name="board'+edu_index+'" onchange="updateResume()">\
					<label>\
						Year of passing\
					</label>\
					<input id="yearofpassing'+edu_index+'" type="text" name="yearofpassing'+edu_index+'" onchange="updateResume()">\
					<label>\
						Percentage / grade\
					</label>\
					<input id="grade'+edu_index+'" type="text" name="grade'+edu_index+'" onchange="updateResume()">\
				</div>';
		edu_index += 1;
		$("#educationgroup").append(data);

	}
	function addAcadAchievements()
	{
		var data = "";
		data =data + '<div class="checkbox">\
							<input type="checkbox" id="acadAchievcheck'+acadAchievements_index+'" checked >\
					</div>\
					<input id="acadAchieve'+acadAchievements_index+'" type="text" name="acadAchieve'+acadAchievements_index+'" onchange="updateResume()">\
					<br>\
				</div>';
		acadAchievements_index += 1;
		$("#acadAchievementsgroup").append(data);
	}
	function addExtraC()
	{
		var data = "";
		data =data + '<div class="checkbox">\
							<input type="checkbox" id="extraentrycheck'+extraC_index+'" checked>\
					</div>\
					<input id="extraentry'+extraC_index+'" type="text" name="extraentry'+extraC_index+'" onchange="updateResume()">\
					<br>\
				</div>';
		extraC_index += 1;
		$("#extraCgroup").append(data);
	}
	$('#contactcheck').change(function () {
		updateResume();
		$("#contactgroup").slideToggle();
	});
	$('#educationcheck').change(function () {
		updateResume();
		$("#educationgroup").slideToggle();
	});
	$('#acadAchievementscheck').change(function () {
		updateResume();
		$("#acadAchievementsgroup").slideToggle();
	});
	$('#workExperiencecheck').change(function () {
		updateResume();
		$("#workExperiencegroup").slideToggle();
	});
	$('#papercheck').change(function () {
		updateResume();
		$("#papersgroup").slideToggle();
	});
	$('#extraCcheck').change(function () {
		updateResume();
		$("#extraCgroup").slideToggle();
	});
	
	function change_template()
	{
		//get the new css
		var result=""
		$.ajax({
    		type: "GET",
    		url: "/homepages/cssapi",
    		data: {css_template: $("#css_template option:selected").text()},
    		async: false,
    		success: function(data){
    					result=data
    					console.log(data)
    				}
    	})
		current_dynamic_css = result;
		updateResume();
	}

	function toggleUpDown()
	{
		$(this).innerHTML = ($(this).innerHTML == '^')?'v':'^';
	}
</script>
<style>
.page{
	/*padding : 10pt;*/
	width : 70%;
	float: left;
	/*height : 1000px;*/
	/*margin: 10pt;*/
	border: solid black 1pt;
	/*background-color: #F4F9FB;*/
}
.fieldname{
	font-weight: bold;
}
.formgroup{
	background-color: #eee;
}
/*.checkbox{

}
.name{
	text-align: left;
	font-size: 35px;
	margin-bottom: -10px;
	padding-bottom: 0px;
	color: #050560;
}*/
.contacts{
	font-size: 16px;
	/*font-weight: bold;*/
	margin-bottom: 10px;
	margin-top: 0px;
	text-align: right;
	color: #050560;

}/*
.section_title{
	font-weight: bold;
	font-size: 16px;
	background-color: #DBE5E9;
	text-align: left;
	color: #050560;
}*/
.list{
	list-style-type: square;
	font-size: 16px;
	margin-left: 20px;
}
table{
	font-size: 16px;
	/*color: #050560;*/
}
td{
	font-size: 14px;
}


</style>

<script>
// For verification of name before submission'
$(function() {
    $('#form').submit(function(e) {
    	e.preventDefault();
    	var rName = $("#rname").val()
    	ret = false
    	$.ajax({
    		type: "GET",
    		url: "/homepages/checkdata",
    		data: {rname: rName},
    		async: false,
    		success: function(data){
    					if(data.valid == "true"){
    						ret = true
    					} 
    					else{
    							alert("Name already in use. Use a new name")
    					}
    				}
    	})
    	if(ret){
    		$.post('/homepages/postdata', $(this).serialize(), function(data){
    			console.log(data);
    			window.location.href="/homepages/view"
    		});
		}
    });
});
</script>

app/views/homepages/home.html.erb
<% provide(:title,"Homepage") %>
<h1> Homepage creator </h1>

<%= button_to "Create Homepage", homepages_create_path, :method => "get", class: "btn btn-primary" %>
<%= button_to "View Homepages", homepages_view_path, :method => "get", class: "btn btn-primary" %>

app/views/homepages/view.html.erb
<div class="row">
	<table class="table table-hover">
	<% @homepage_list.each do |homepage| %>
		<tr> <td><%= homepage.homepage_name %></td><td> 
			<%= link_to "Delete", homepages_delete_path(homepage_id: homepage.id), method: :delete, confirm: "Are you sure? All data for this resume will be lost" %> </td> 
			<td>Download 
			<%= link_to "html", homepages_download_path(homepage_id: homepage.id) %> </td> 
		</tr>
	<% end %>
	</table>
</div>