config/routes.rb
TestApp::Application.routes.draw do
  get "users/new"

  mathjax 'mathjax'
  root to: 'static_pages#home'

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  resources :resumes, only: [ :home, :createpage, :create, :postdata , :checkdata, :viewlist, :viewedit , :delete, :createtemplate, :cssapi, :checkcssfile, :postcssfile] 

  resources :homepages, only: [ :home, :create, :postdata, :view, :delete, :download, :checkdata, :cssapi ]

  match '/signup', to: "users#new"
  match "/help", to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/resumes', to: 'resumes#home'
  match '/resumes/createpage', to: 'resumes#createpage'
  match '/homepages', to: 'homepages#home'

  
  match '/resumes/postdata', to: 'resumes#postdata', via: :post
  match '/resumes/checkdata', to: 'resumes#checkdata', via: :get
  match '/resumes/viewlist', to: 'resumes#viewlist'
  match '/resumes/viewedit', to: 'resumes#viewedit'
  match '/resumes/delete', to: 'resumes#delete'
  match '/resumes/createtemplate', to: 'resumes#createtemplate'
  match '/resumes/download', to: 'resumes#download'
  match '/resumes/cssapi', to: "resumes#cssapi", via: :get
  match '/resumes/checkcssfile', to: "resumes#checkcssfile", via: :get
  match '/resumes/postcssfile', to: "resumes#postcssfile", via: :post

  match '/homepages/create', to: 'homepages#create'
  match '/homepages/postdata',to: 'homepages#postdata', via: :post
  match '/homepages/view', to:'homepages#view'
  match '/homepages/delete', to:'homepages#delete'
  match '/homepages/checkdata', to:'homepages#checkdata'
  match '/homepages/download', to:'homepages#download'
  match '/homepages/cssapi', to: "homepages#cssapi", via: :get

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController

	before_filter :signed_in_user
	#before_filter :signed_in_user, only: [ :home ] 

	def home
	end

	def createpage
		@css_list = ResumesCssTemplate.all
	end

	def create

	end

	def viewlist
		@resume_list = current_user.resume_relations.all
	end

	def postdata
		ActiveRecord::Base.transaction do
		#creates new with this data
		#destroy session variables after update TODO
		if !(session[:existing].nil?)
			@res_id = session[:resume_id];
			if !(current_user.resume_relations.find(@res_id).nil?)
				current_user.resume_relations.find(@res_id).destroy
			end
			session.delete(:existing)
			session.delete(:resume_id)
		end
			@rname = params[:rname]
			if @rname.blank?
				flash[:error] = "Blank name not allowed. You forced the button to click. Now we force you to reenter the data"
				redirect_to resumes_createpage_path
			end
			
			bootstrap = File.read(Rails.root.join('public','bootstrap.min.css'));
			file = StringIO.new('<html><body><script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><style>' + bootstrap + '</style>' + params[:htmlpage] + '</body></html>')

			file.class.class_eval { attr_accessor :original_filename, :content_type }
  			file.original_filename = @rname+".html"
  			file.content_type = "text/html" # you could set this manually aswell if needed e.g 'application/pdf'
			@old_resume = current_user.resume_relations.find_by_resume_filename(@rname)
			if @old_resume.nil?
				
				@new_resume_relations_entry = current_user.resume_relations.build(resume_filename: @rname, resume_html: file)

				@new_resume_relations_entry.save()
				@new_id = @new_resume_relations_entry.id

				#save the actual resume

				#css_template_name
				@new_resume_relations_entry.resume_data_values.build(field_name: "css_template", field_data: params[:css_template]).save()
				
				#name
				@name = params[:name]
				@resume_data_name = @new_resume_relations_entry.resume_data_values.build(field_name: "name", field_data: @name)
				@resume_data_name.save()


				#contact
				@contactcheck = params[:contactcheck]
				@new_resume_relations_entry.resume_data_values.build(field_name: "contactcheck", field_data: @contactcheck).save()

				@email = params[:email]
				@new_resume_relations_entry.resume_data_values.build(field_name: "email", field_data: @email).save()				

				@contact = params[:contact]
				@new_resume_relations_entry.resume_data_values.build(field_name: "contact", field_data: @contact).save()

				#education
				@edu_check = params[:educationcheck]
				@new_resume_relations_entry.resume_data_values.build(field_name: "educationcheck", field_data: @edu_check).save()

				e_index = params[:edu_index]
				@new_resume_relations_entry.resume_data_values.build(field_name: "edu_index", field_data: e_index).save()
				no = Integer(e_index) -1;
				if no>0
					(0..no).each do |i|
						is = i.to_s

						pn = "educheck"+is
						@new_resume_relations_entry.resume_data_values.build(field_name: pn, field_data: params[pn.to_sym]).save()

						pn = "class"+is
						@new_resume_relations_entry.resume_data_values.build(field_name: pn, field_data: params[pn.to_sym]).save()

						pn = "board"+is
						@new_resume_relations_entry.resume_data_values.build(field_name: pn, field_data: params[pn.to_sym]).save()

						pn = "yearofpassing"+is
						@new_resume_relations_entry.resume_data_values.build(field_name: pn, field_data: params[pn.to_sym]).save()

						pn = "grade"+is
						@new_resume_relations_entry.resume_data_values.build(field_name: pn, field_data: params[pn.to_sym]).save()
					end
				end
				#academic acheivements
				@acad_achev_check = params[:acadAchievementscheck]
				@new_resume_relations_entry.resume_data_values.build(field_name: "acadAchievementscheck", field_data: @acad_achev_check).save()


				e_index = params[:acadachievements_index]
				@new_resume_relations_entry.resume_data_values.build(field_name: "acadachievements_index", field_data: e_index).save()
				no = Integer(e_index) - 1
				if no>0
					(0..no).each do |i|
						is = i.to_s

						pn = "acadAchievcheck"+is
						@new_resume_relations_entry.resume_data_values.build(field_name: pn, field_data: params[pn.to_sym]).save()


						pn = "acadAchieve"+is
						@new_resume_relations_entry.resume_data_values.build(field_name: pn, field_data: params[pn.to_sym]).save()
					end
				end
				#work ex
				@work_ex_check = params[:workExperiencecheck]
				@new_resume_relations_entry.resume_data_values.build(field_name: "workExperiencecheck", field_data: @work_ex_check).save()

				@ind = params[:workexp_index]
				@new_resume_relations_entry.resume_data_values.build(field_name: "workexp_index", field_data: @ind).save()
				no = Integer(@ind) -1
				if no>0
					(0..no).each do |i|
						is = i.to_s

						pn = "workExpEntrycheck"+is
						@new_resume_relations_entry.resume_data_values.build(field_name: pn, field_data: params[pn.to_sym]).save()

						pn = "workexpentry"+is
						@new_resume_relations_entry.resume_data_values.build(field_name: pn, field_data: params[pn.to_sym]).save()
					end				  
				end
				#papers
				
				@paper_check = params[:papercheck]
				@new_resume_relations_entry.resume_data_values.build(field_name: "papercheck", field_data: @paper_check).save()

				@ind = params[:paper_index]
				@new_resume_relations_entry.resume_data_values.build(field_name: "paper_index", field_data: @ind).save()
				no = Integer(@ind) -1
				if no>0
					(0..no).each do |i|
						is = i.to_s

						pn = "paperEntrycheck"+is
						@new_resume_relations_entry.resume_data_values.build(field_name: pn, field_data: params[pn.to_sym]).save()


						pn = "paperEntry"+is
						@new_resume_relations_entry.resume_data_values.build(field_name: pn, field_data: params[pn.to_sym]).save()
					end				  
				end
				#extra c
				@extra_c_check = params[:extraCcheck]
				@new_resume_relations_entry.resume_data_values.build(field_name: "extraCcheck", field_data: @extra_c_check).save()

				@ind = params[:extrac_index]
				@new_resume_relations_entry.resume_data_values.build(field_name: "extrac_index", field_data: @ind).save()
				no = Integer(@ind) -1
				if no>0
					(0..no).each do |i|
						is = i.to_s

						pn = "extraentrycheck"+is
						@new_resume_relations_entry.resume_data_values.build(field_name: pn, field_data: params[pn.to_sym]).save()


						pn = "extraentry"+is
						@new_resume_relations_entry.resume_data_values.build(field_name: pn, field_data: params[pn.to_sym]).save()
					end				  
				end
				#done woohoo
				#ends here

				flash[:success] =  "Successfully created resume!"
				redirect_to resumes_viewlist_path
				#redirect_to resume_view_path
			else
				flash[:error] = "Name already in use. You forced the button to click. Now we force you to reenter the data"
				redirect_to resumes_createpage_path
			end
			#change this to created path
			file.close
		end
	end

	def checkdata
		@new_name = params[:rname]
		@old_r = current_user.resume_relations.find_by_resume_filename(@new_name)
		if @old_r.blank? && !(@new_name.blank?)
			render :json => {"valid" => "true"}
		else
			render :json => {"valid" => "false"}
		end
	end

	def viewedit
		@css_list = ResumesCssTemplate.all
		@res_id = params[:resume_id]
		session[:existing] = true
		session[:resume_id] = @res_id
		@r = current_user.resume_relations.find(@res_id).resume_data_values
		@file_name = current_user.resume_relations.find(@res_id).resume_filename
	end

	def delete
		@res_id = params[:resume_id]
		@rec = current_user.resume_relations.find(@res_id)
		@rec.destroy
		flash[:success] = "Deleted the resume successfully"
		redirect_to resumes_viewlist_path
	end

	def createtemplate
	end

	def download
		@resume = current_user.resume_relations.find(params[:resume_id])
		
		if @resume.nil?
			flash[:error] = "Invalid parameters entered"
			redirect_to resumes_viewlist_path
		end
		PandocRuby.allow_file_paths = true
		@reqFor = params[:format]
		case @reqFor
			when "html"
				send_file @resume.resume_html.path, filename: @resume.resume_filename, type: "text/html", disposition: 'inline'
			when "pdf"
				send_data WickedPdf.new.pdf_from_html_file(@resume.resume_html.path, :javascript_delay=>5000), filename: "download.pdf", type: "application/pdf", dispostion: "inline"	
			when "latex"
				send_data PandocRuby.convert(@resume.resume_html.path, :from => :html, :to => :latex), filename: "download.tex", type: "application/x-tex", dispostion: "inline"
			when "markdown"
				send_data PandocRuby.convert(@resume.resume_html.path, :from => :html, :to => :markdown), filename: "download.md", type: "text/markdown", dispostion: "inline"
			when "json"
				render json: @resume.resume_data_values
			else
				flash[:error] = "Invalid/unsupported format specified"
				redirect_to root_url
		end  
	end

	def cssapi
		@css_fname = params[:css_template]
		send_data Paperclip.io_adapters.for(ResumesCssTemplate.find_by_template_name(@css_fname).template_file).read
	end

	def checkcssfile
		@new_name = params[:file_name]
		@old_r = ResumesCssTemplate.find_by_template_name(@new_name)
		if @old_r.blank? && !(@new_name.blank?)
			render :json => {"valid" => "true"}
		else
			render :json => {"valid" => "false"}
		end
	end

	def postcssfile
		ActiveRecord::Base.transaction do
			@new_name = params[:file_name]
			@old_r = ResumesCssTemplate.find_by_template_name(@new_name)
			if !(@old_r.blank?) || (@new_name.blank?)
				flash[:error] = "You forcibly posted an invalid css file. Your css file will be lost"
				redirect_to root_url
			else
				file = StringIO.new('<style>' + params[:css_res] + '</style>')

				file.class.class_eval { attr_accessor :original_filename, :content_type }
	  			file.original_filename = @new_name + ".css"
	  			file.content_type = "text/css" # you could set this manually aswell if needed e.g 'application/pdf'
				ResumesCssTemplate.new(template_name:@new_name, template_file: file).save()

app/helpers/resumes_helper.rb
module ResumesHelper
	def getv(res,param)
		b = res.find_by_field_name(param)
		if b.nil?
			return 0
		else
			return b.field_data
		end
	end
end

app/views/resumes/createpage.html.erb
<%= provide(:title, "Create Resume" ) %>
<div id="create_page" class="row">
	<div class="col-md-6">
		<div id="resume" class="page"></div>
	</div>

	<div class="col-md-6" id="form_div">
		<!-- move this to an appropriate file -->
		<%= form_tag(resumes_postdata_path, method: "post", id: "form") do %>
			<label class="fieldname">
				File Name :
			</label>
			<input id="rname" type="text" name="rname">
			<br>
			<br>
			<label class="fieldname">
				Template Name :
			</label>
			<select id="css_template" name="css_template" form="form" onchange="change_template()">
				<% @css_list.each do |item| %>
					<option value="<%= item.template_name %>"><%= item.template_name %></option>
				<% end %>
			</select>
			<hr>
			<label class="fieldname">Resume data:</label>
			<label class="fieldname">
				Name :
			</label>
			<input id="name" type="text" name="name" onchange="updateResume()">
			<br>
			<div class="checkbox">
				<label class="fieldname">
					<button type="button" onclick="$('#contactgroup').slideToggle(); toggleUpDown();">^</button><input type="checkbox" id="contactcheck" name="contactcheck" checked> Contact :
				</label>
			</div>
			<div class="formgroup" id="contactgroup">
				<label>
					Email id :
				</label>
				<input id="email" type="text" name="email" onchange="updateResume()">
				<br>
				<label>
					Contact number :
				</label>
				<input id="contact" type="text" name="contact" onchange="updateResume()">
			</div>
			<div class="checkbox">
				<label class="fieldname">
					<button type="button" onclick="$('#educationgroup').slideToggle(); toggleUpDown();">^</button><input type="checkbox" id="educationcheck" name = "educationcheck" checked> Education :
				</label>
			</div>
			<div class="formgroup" id="educationgroup">
				<button type="button" onclick="addEducation()">+</button>
			</div>

			
			<div class="checkbox">
				<label class="fieldname">
					<button type="button" onclick="$('#acadAchievementsgroup').slideToggle(); toggleUpDown();">^</button><input type="checkbox" id="acadAchievementscheck" name="acadAchievementscheck"checked> Academic Achievements :
				</label>
			</div>
			<div class="formgroup" id="acadAchievementsgroup">
				<button type="button" onclick="addAcadAchievements()">+</button>
			</div>

			<div class="checkbox">
				<label class="fieldname">
					<button type="button" onclick="$('#workExperiencegroup').slideToggle(); toggleUpDown();">^</button><input type="checkbox" id="workExperiencecheck" name="workExperiencecheck"checked> Work Experience :
				</label>
			</div>
			<div class="formgroup" id="workExperiencegroup">
				<button type="button" onclick="addWorkExperience()">+</button>
			</div>

			<div class="checkbox">
				<label class="fieldname">
					<button type="button" onclick="$('#papersgroup').slideToggle(); toggleUpDown();">^</button><input type="checkbox" id="papercheck" name="papercheck"checked> Papers Published :
				</label>
			</div>
			<div class="formgroup" id="papersgroup">
				<button type="button" onclick="addPaper()">+</button>
			</div>

			<div class="checkbox">
				<label class="fieldname">
					<button type="button" onclick="$('#extraCgroup').slideToggle(); toggleUpDown();">^</button><input type="checkbox" id="extraCcheck" name="extraCcheck"checked> Extra Curricular Activities :
				</label>
			</div>
			<div class="formgroup" id="extraCgroup">
				<button type="button" onclick="addExtraC()">+</button>
			</div>

			<input type="submit" class="btn btn-primary">
			<input type="hidden" id="htmlpage" name="htmlpage" />
			<input type="hidden" id="edu_index" name = "edu_index"/>
			<input type="hidden" id="acadachievements_index" name = "acadachievements_index"/>
			<input type="hidden" id="workexp_index" name = "workexp_index"/>
			<input type="hidden" id="paper_index" name = "paper_index"/>
			<input type="hidden" id="extrac_index" name = "extrac_index"/>
		<% end %>
	</div>
</div>
<div class="modal"><!-- Place at bottom of page --></div>
<!--<script src="http://builds.handlebarsjs.com.s3.amazonaws.com/handlebars-v1.3.0.js"></script>
<script src="http://builds.emberjs.com/tags/v1.5.0/ember.js"></script> -->


<script>
	var edu_index=0;
	var acadAchievements_index=0;
	var workExp_index=0;
	var paper_index=0;
	var extraC_index=0;
	var current_dynamic_css = '';
	function updateResume()
	{
		$('#edu_index').val(edu_index);
		$('#acadachievements_index').val(acadAchievements_index);
		$('#workexp_index').val(workExp_index);
		$('#paper_index').val(paper_index);
		$('#extrac_index').val(extraC_index);
		var data = "";
		data = data + "<h1 class='name'>" + getData("name") + "</h1>";
		data = data + "<hr>";
		if(check("contactcheck"))
		{
			data = data + "<div class='contacts'>";
			data = data + "Email id : " + getData("email") + "<br>" + "Contact : " + getData('contact')+ "</div>";
		}
		// data = data + "<hr>";
		if(check("educationcheck"))
		{
			data = data + '<label class="section_title">Educational Qualifications</label><table class="table table-condensed">\
							  <tr>\
							  	<th>Class</th>\
							  	<th>Board / University</th>\
							  	<th>Year of Passing</th>\
							  	<th>Grade / percentage</th>\
							  </tr>'
			var i;
			for(i=0; i<edu_index; i++)
			{
				if(check("educheck"+i))
				{
					data = data + "<tr><td>"+getData("class"+i)+"</td><td>"+getData("board"+i)+"</td><td>"+getData("yearofpassing"+i)+"</td><td>"+getData("grade"+i)+"</td><td></tr>"
				}
			}
			data = data + "</table>";
		}
		if(check("acadAchievementscheck"))
		{
			data = data + '<label class="section_title">Academic Achievements</label>\
							<ul class="list">'
			var i;
			for(i=0; i<acadAchievements_index; i++)
			{
				if(check("acadAchievcheck"+i))
				{
					data = data + "<li>" + getData("acadAchieve"+i)+"</li>"
				}
			}
			data = data + "</ul>";
		}

		if(check("workExperiencecheck"))
		{
			data = data + '<label class="section_title">Work Experience</label>\
							<ul class="list">'
			var i;
			for(i=0; i<workExp_index; i++)
			{
				if(check("workExpEntrycheck"+i))
				{
					data = data + "<li>" + getData("workexpentry"+i)+"</li>"
				}
			}
			data = data + "</ul>";
		}
		if(check("papercheck"))
		{
			data = data + '<label class="section_title">Papers Published</label>\
							<ul class="list">'
			var i;
			for(i=0; i<paper_index; i++)
			{
				if(check("paperEntryCheck"+i))
				{
					data = data + "<li>" + getData("paperEntry"+i)+"</li>"
				}
			}
			data = data + "</ul>";
		}
		if(check("extraCcheck"))
		{
			data = data + '<label class="section_title">Extra Curricular Achievements</label>\
							<ul class="list">'
			var i;
			for(i=0; i<extraC_index; i++)
			{
				if(check("extraentrycheck"+i))
				{
					data = data + "<li>" + getData("extraentry"+i)+"</li>"
				}
			}
			data = data + "</ul>";
		}
		data = data + "<style id='dynamic_css'>"+current_dynamic_css+"</style>";
		data = data + ''
		// data = data + '<label class="section_title">Hobbies</label>'

		// if(check("educationcheck"))
		// {}
		
		document.getElementById("resume").innerHTML = data;

		$("#htmlpage").val(data)
		MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
		
	}
	function getData(field)
	{
		var s = document.getElementById(field).value;
		//write code to remove tags etc.
		// s=s.replace(/&amp;/g,'&amp;amp;');
		// s=s.replace(/&lt;/g,'&amp;lt;');
		// s=s.replace(/&gt;/g,'&amp;gt;');
		// s=s.replace(/\n/g,'&lt;br /&gt;\n');
		// s=s.replace(/\r/g,'');
		return s;
	}
	function check(str)
	{
		if(document.getElementById(str).checked)
			return true;
		else
			return false;
	}
	function addEducation()
	{
		var data = "";
		data =data + '<div class="checkbox">\
						<label class="fieldname">\
							<input type="checkbox" id="educheck'+edu_index+'" name ="educheck'+edu_index+'"checked> Class :\
						</label>\
					</div>\
					<input id="class'+edu_index+'" type="text" name="class'+edu_index+'" onchange="updateResume()">\
					<br>\
					<label>\
						Board / University\
					</label>\
					<input id="board'+edu_index+'" type="text" name="board'+edu_index+'" onchange="updateResume()">\
					<label>\
						Year of passing\
					</label>\
					<input id="yearofpassing'+edu_index+'" type="text" name="yearofpassing'+edu_index+'" onchange="updateResume()">\
					<label>\
						Percentage / grade\
					</label>\
					<input id="grade'+edu_index+'" type="text" name="grade'+edu_index+'" onchange="updateResume()">\
				</div>';
		edu_index += 1;
		$("#educationgroup").append(data);
		updateResume();
	}
	function addAcadAchievements()
	{
		var data = "";
		data =data + '<div class="checkbox">\
							<input type="checkbox" id="acadAchievcheck'+acadAchievements_index+'" name="acadAchievcheck'+acadAchievements_index+'" checked>\
					</div>\
					<input id="acadAchieve'+acadAchievements_index+'" type="text" name="acadAchieve'+acadAchievements_index+'" onchange="updateResume()">\
					<br>\
				</div>';
		acadAchievements_index += 1;
		$("#acadAchievementsgroup").append(data);
		updateResume();
	}
	function addWorkExperience()
	{
		var data = "";
		data =data + '<div class="checkbox">\
							<input type="checkbox" id="workExpEntrycheck'+workExp_index+'" name="workExpEntrycheck'+workExp_index+'" checked>\
					</div>\
					<input id="workexpentry'+workExp_index+'" type="text" name="workexpentry'+workExp_index+'" onchange="updateResume()">\
					<br>\
				</div>';
		workExp_index += 1;
		$("#workExperiencegroup").append(data);
		updateResume();
	}
	function addPaper()
	{
		var data = "";
		data =data + '<div class="checkbox">\
							<input type="checkbox" id="paperEntryCheck'+paper_index+'"  name ="paperEntryCheck'+paper_index+'" checked>\
					</div>\
					<input id="paperEntry'+paper_index+'" type="text" name="paperEntry'+paper_index+'" onchange="updateResume()">\
					<br>\
				</div>';
		paper_index += 1;
		$("#papersgroup").append(data);
		updateResume();
	}
	function addExtraC()
	{
		var data = "";
		data =data + '<div class="checkbox">\
							<input type="checkbox" id="extraentrycheck'+extraC_index+'" name="extraentrycheck'+extraC_index+'" checked>\
					</div>\
					<input id="extraentry'+extraC_index+'" type="text" name="extraentry'+extraC_index+'" onchange="updateResume()">\
					<br>\
				</div>';
		extraC_index += 1;
		$("#extraCgroup").append(data);
		updateresume();
	}
	$('#contactcheck').change(function () {
		updateResume();
		$("#contactgroup").slideToggle();
	});
	$('#educationcheck').change(function () {
		updateResume();
		$("#educationgroup").slideToggle();
	});
	$('#acadAchievementscheck').change(function () {
		updateResume();
		$("#acadAchievementsgroup").slideToggle();
	});
	$('#workExperiencecheck').change(function () {
		updateResume();
		$("#workExperiencegroup").slideToggle();
	});
	$('#papercheck').change(function () {
		updateResume();
		$("#papersgroup").slideToggle();
	});
	$('#extraCcheck').change(function () {
		updateResume();
		$("#extraCgroup").slideToggle();
	});
	function change_template()
	{
		//get the new css
		var result=""
		$.ajax({
    		type: "GET",
    		url: "/resumes/cssapi",
    		data: {css_template: $("#css_template option:selected").text()},
    		async: false,
    		success: function(data){
    					result=data
    					console.log(data)
    				}
    	})
		current_dynamic_css = result;
		updateResume();
	}
	function toggleUpDown()
	{
		if($(this).innerHTML == '^')
			$(this).innerHTML = 'v';
		else
			$(this).innerHTML = '^';
	}
</script>
<style>
.page{
		padding : 10pt;
		width : 60%;
		height : 1000px;
		margin: 10pt;
		border: solid black 1pt;
	}
	.fieldname{
		font-weight: bold;
	}
	.formgroup{
		
	}
	.checkbox{

	}

</style>

<script>
// For verification of name before submission'
$(function() {
    $('#form').submit(function(e) {
    	e.preventDefault();
    	var rName = $("#rname").val()
    	ret = false
    	$.ajax({
    		type: "GET",
    		url: "/resumes/checkdata",
    		data: {rname: rName},
    		async: false,
    		success: function(data){
    					if(data.valid == "true"){
    						ret = true
    					} 
    					else{
    							alert("Name already in use. Use a new name")
    					}
    				}
    	})
    	if(ret){
    		$.post('/resumes/postdata', $(this).serialize(), function(data){
    			alert("Success!")
    			window.location.href= "/resumes/viewlist"
    		});
		}
    });
});
</script>

app/views/resumes/home.html.erb
<% provide(:title, "Resume Home") %>

<%= button_to 'Create Resume', resumes_createpage_path , :method => "get", class:"btn btn-primary" %> 

<%= button_to 'Existing Resume', resumes_viewlist_path , :method => "get", class:"btn btn-primary" %> 

<%= button_to "Create Template", resumes_createtemplate_path, :method => "get", class: "btn btn-primary" %>

app/views/resumes/postdata.html.erb
<%= @vars %>

app/views/resumes/viewlist.html.erb
<div class="row">
	<table class="table table-hover">
	<% @resume_list.each do |resume| %>
		<tr> <td><%= resume.resume_filename %></td><td> <%= link_to "View/Edit", resumes_viewedit_path(:resume_id => resume.id) %> </td><td> 
			<%= link_to "Delete", resumes_delete_path(resume_id: resume.id), method: :delete, confirm: "Are you sure? All data for this resume will be lost" %> </td> 
			<td>Download 
			<%= link_to "html", resumes_download_path(resume_id: resume.id, format: "html" ) %> </td> 
			<td><%= link_to "pdf", resumes_download_path(resume_id: resume.id, format: "pdf" ) %></td>
			<td><%= link_to "latex", resumes_download_path(resume_id: resume.id, format: "latex" ) %></td>
			<td><%= link_to "json", resumes_download_path(resume_id: resume.id, format: "json" ) %></td>
		</tr>
	<% end %>
	</table>
</div>