config/routes.rb
TestApp::Application.routes.draw do
  get "users/new"

  mathjax 'mathjax'
  root to: 'static_pages#home'

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  resources :resumes, only: [ :home, :createpage, :create, :postdata , :checkdata, :viewlist, :viewedit , :delete, :createtemplate, :cssapi, :checkcssfile, :postcssfile] 

  resources :homepages, only: [ :home, :create, :postdata, :view, :delete, :download, :checkdata, :cssapi ]

  match '/signup', to: "users#new"
  match "/help", to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/resumes', to: 'resumes#home'
  match '/resumes/createpage', to: 'resumes#createpage'
  match '/homepages', to: 'homepages#home'

  
  match '/resumes/postdata', to: 'resumes#postdata', via: :post
  match '/resumes/checkdata', to: 'resumes#checkdata', via: :get
  match '/resumes/viewlist', to: 'resumes#viewlist'
  match '/resumes/viewedit', to: 'resumes#viewedit'
  match '/resumes/delete', to: 'resumes#delete'
  match '/resumes/createtemplate', to: 'resumes#createtemplate'
  match '/resumes/download', to: 'resumes#download'
  match '/resumes/cssapi', to: "resumes#cssapi", via: :get
  match '/resumes/checkcssfile', to: "resumes#checkcssfile", via: :get
  match '/resumes/postcssfile', to: "resumes#postcssfile", via: :post

  match '/homepages/create', to: 'homepages#create'
  match '/homepages/postdata',to: 'homepages#postdata', via: :post
  match '/homepages/view', to:'homepages#view'
  match '/homepages/delete', to:'homepages#delete'
  match '/homepages/checkdata', to:'homepages#checkdata'
  match '/homepages/download', to:'homepages#download'
  match '/homepages/cssapi', to: "homepages#cssapi", via: :get

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<nav>
				<ul class = "nav pull-left">
					<li>
						<% if signed_in? %>
							Hi <%= current_user.name %> 
						<% else %>
							<%= link_to "Template Creator", root_path, id: "logo" %>
						<% end %>
					</li>
				</ul>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<% if signed_in? %>
						<li><%= link_to "Users", users_path %></li>
						<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account 
							<b class="caret"></b>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li>
								<%= link_to "Sign out", signout_path, method: "delete" %>
								</li>
							</ul>
						</li>
						</a>
					<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
			<%= stylesheet_link_tag "application", media: "all" %>
			<%= javascript_include_tag "application" %>
			<%= csrf_meta_tags %>
			<%= yield(:head) %>
			<%= render 'layouts/shim' %>
</head>
<body>
	<%= mathjax_tag %>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>

		<%= yield %>
	</div>
<div class="modal"><!-- Place at bottom of page --></div>

<style id="coolloader">
.modal {
    display:    none;
    position:   fixed;
    z-index:    1000;
    top:        100px;
    height:     50%;
    width:      50%;
    background: rgba( 255, 255, 255, 1 ) 
                url('/loading.gif') 
                50% 50% 
                no-repeat;
}

body.loading {
    overflow: auto;   
}

body.loading .modal {
    display: block;
}
</style>

<script id="cooljsloading">
	$body = $("body");

	$(document).on({
	    ajaxStart: function() { $body.addClass("loading");    },
	     ajaxStop: function() { $body.removeClass("loading"); }    
	});

</script>


</body>
</html>